### ISSUE TITLE
PyTooling incompatible

### ISSUE THREAD

**Issue by kaiteu** [Paebbels/pyVersioning#15]
Error is Triggered by the following module:  
`from pyTooling.Versioning import SemVersion`

**Comment by Paebbels** [comment]
pyVersioning has no upper version limit for `pyTooling`.  
This will be added with next version.

The reason is `pyTooling` renamed the class for v5.0.0.

**Comment by Paebbels** [comment]
@kaiteu This problem is blocking a release: https://github.com/buildthedocs/btd/issues/11

I'll see for a workaround.

**Comment by Paebbels** [comment]
I added a new group of "after-installation unit tests".

4 out-of 6 are failing, but I should be able to cover such effects now and in future releases. Working on a fix.

**Comment by Paebbels** [comment]
Ok, all additional tests are now passing. I'll start the release process in the evening. (See also #17)

**Comment by Paebbels** [comment]
[v0.12.0](https://github.com/Paebbels/pyVersioning/releases/tag/v0.12.0) has been released a few days before.
